package com.example.demo.DO;

import java.io.Serializable;

public class ScDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.sno
     *
     * @mbg.generated
     */
    private String sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.cno
     *
     * @mbg.generated
     */
    private String cno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.score
     *
     * @mbg.generated
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.sno
     *
     * @return the value of sc.sno
     *
     * @mbg.generated
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.sno
     *
     * @param sno the value for sc.sno
     *
     * @mbg.generated
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.cno
     *
     * @return the value of sc.cno
     *
     * @mbg.generated
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.cno
     *
     * @param cno the value for sc.cno
     *
     * @mbg.generated
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.score
     *
     * @return the value of sc.score
     *
     * @mbg.generated
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.score
     *
     * @param score the value for sc.score
     *
     * @mbg.generated
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sno=").append(sno);
        sb.append(", cno=").append(cno);
        sb.append(", score=").append(score);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}