package com.example.demo.DO;

import java.io.Serializable;

public class StudentDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sno
     *
     * @mbg.generated
     */
    private Integer sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sage
     *
     * @mbg.generated
     */
    private Integer sage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sdept
     *
     * @mbg.generated
     */
    private String sdept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sno
     *
     * @return the value of student.Sno
     *
     * @mbg.generated
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sno
     *
     * @param sno the value for student.Sno
     *
     * @mbg.generated
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sname
     *
     * @return the value of student.Sname
     *
     * @mbg.generated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sname
     *
     * @param sname the value for student.Sname
     *
     * @mbg.generated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sex
     *
     * @return the value of student.Sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sex
     *
     * @param sex the value for student.Sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sage
     *
     * @return the value of student.Sage
     *
     * @mbg.generated
     */
    public Integer getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sage
     *
     * @param sage the value for student.Sage
     *
     * @mbg.generated
     */
    public void setSage(Integer sage) {
        this.sage = sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sdept
     *
     * @return the value of student.Sdept
     *
     * @mbg.generated
     */
    public String getSdept() {
        return sdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sdept
     *
     * @param sdept the value for student.Sdept
     *
     * @mbg.generated
     */
    public void setSdept(String sdept) {
        this.sdept = sdept == null ? null : sdept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sno=").append(sno);
        sb.append(", sname=").append(sname);
        sb.append(", sex=").append(sex);
        sb.append(", sage=").append(sage);
        sb.append(", sdept=").append(sdept);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}