package com.example.demo.DAO;

import com.example.demo.DO.ScDO;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("sno") String sno, @Param("cno") String cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated
     */
    int insert(ScDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated
     */
    ScDO selectByPrimaryKey(@Param("sno") String sno, @Param("cno") String cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated
     */
    List<ScDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ScDO record);
}